# Generated stubs — do not edit by hand.
# Regenerated by scripts/generate_stubs.sh
# feature_store.proto SHA256: 4e0816c8680b6ec65b1b401c36778cfc78bfcbb6ac15bc1cd80d0e8a60496536
# inference.proto      SHA256: 0e11b9f3c0fcb9aed3ffef49abcec3c6c64bda59e90ca1adde195860e705d615

# Re-export generated modules at short names for ergonomic imports:
#   from ml_inference_svc.grpc_stubs import inference_pb2, feature_store_pb2
from ml_inference_svc.grpc_stubs.judicialpredict.data_plane.feature_store.v1 import (
    feature_store_pb2,
)
from ml_inference_svc.grpc_stubs.judicialpredict.ml_plane.inference.v1 import (
    inference_pb2,
)

__all__ = ["feature_store_pb2", "inference_pb2"]
