#!/bin/bash
# JudicialPredict — daily progress-report generator (auth-independent)
# Reads Plane mirror + git activity, produces a daily/weekly digest, emails Braun.

set -uo pipefail

PROJECT_DIR="/opt/ai-elevate/gigforge/projects/judicialpredict"
REPORTS="$PROJECT_DIR/reports"
MIRROR="$PROJECT_DIR/.plane-mirror"
TODAY=$(date -u +%Y-%m-%d)
NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)
PERIOD="${1:-daily}"  # daily | weekly | sprint

mkdir -p "$REPORTS"

# Pull latest mirror
"$PROJECT_DIR/jp-sync.sh" >/dev/null 2>&1

OUT_FILE="$REPORTS/${PERIOD}-${TODAY}.md"

python3 - <<PYEOF > "$OUT_FILE"
import json, datetime, subprocess, os
mirror = "$MIRROR"
period = "$PERIOD"
today = "$TODAY"

def load(p):
    try:
        with open(p) as f:
            return json.load(f)
    except Exception:
        return {}

issues_data = load(f"{mirror}/issues.json")
cycles_data = load(f"{mirror}/cycles.json")
issues = issues_data.get("results", []) if isinstance(issues_data, dict) else issues_data

# State id → name (looked up via DB earlier; hardcoded for now — fetched lazily)
STATE_NAMES = {
    "effd4c59-3f15-4801-89c1-1b6f9b409519": "Backlog",
    "e7ad40c6-2e0b-407c-815d-4f44b175535b": "Ready",
    "b3146829-9a6a-4fe6-9a64-89d66695873b": "In Progress",
    "1807baeb-45f1-4abb-b8b3-f494e9229c89": "In Review",
    "99f6e942-ad50-432e-a790-f08e87db2569": "In Testing",
    "3f849f59-d069-49f7-9cfd-8d842f21829d": "In Staging",
    "780127a0-7546-446b-ae88-29f7d6b1c5a7": "In Production",
    "34833f6a-642d-4ff2-b875-bd649fa8ff0b": "Cancelled",
}

# State counts + per-agent breakdown
state_counts = {}
agent_counts = {}
recent_changes = []
for i in issues:
    s = STATE_NAMES.get(i.get("state",""), "Unknown")
    state_counts[s] = state_counts.get(s, 0) + 1
    name = i.get("name","")
    seq = i.get("sequence_id","?")
    updated = i.get("updated_at","")
    if updated and updated[:10] == today:
        recent_changes.append((seq, name, s, updated))

# Print report
print(f"# JudicialPredict — {period.title()} Progress Report")
print(f"\n**Date:** {today}")
print(f"**Generated:** {datetime.datetime.utcnow().isoformat()}Z (auth-independent — reads from Plane mirror snapshot)")
print(f"\n**Plane project:** http://localhost:8801 → workspace `gigforge` → project JudicialPredict (JP)")
print(f"**Spec:** {os.path.dirname(mirror)}/judicialpredict-v2-spec.md (v2.13)")
print(f"\n## Workflow snapshot")
print(f"\n| State | Count |")
print(f"|-------|-------|")
for s in ["Backlog","Ready","In Progress","In Review","In Testing","In Staging","In Production","Cancelled"]:
    if s in state_counts:
        print(f"| {s} | {state_counts[s]} |")
print(f"| **Total** | **{len(issues)}** |")

print(f"\n## Activity in last 24h")
if recent_changes:
    print(f"\n| Issue | Title | State | Updated |")
    print(f"|-------|-------|-------|---------|")
    for seq, n, s, u in sorted(recent_changes):
        print(f"| JP-{seq} | {n[:60]} | {s} | {u[:19]}Z |")
else:
    print(f"\nNo issue updates in the last 24h.")

# Recent commits in local repo (this is on production server, so report git activity if /home/bbrelin/judicialpredict exists)
print(f"\n## Repository activity")
print(f"\nLocal repo at `/home/bbrelin/judicialpredict` lives on Braun's workstation, not the production server. PM should request commit-log mirroring from Braun for richer reports.")

# Active blockers (issues stuck > 5 days in same state — placeholder, would need state history)
print(f"\n## Open dispatches and blockers")
print(f"\n- See `/opt/ai-elevate/gigforge/projects/judicialpredict/PENDING-PM-DISPATCH.md` for current blocker (gateway auth).")

print(f"\n## Sprint 1 cycle")
sprint = next((c for c in (cycles_data.get("results", []) if isinstance(cycles_data, dict) else cycles_data) if "Sprint 1" in c.get("name","")), None)
if sprint:
    print(f"\n- **Name:** {sprint.get('name')}")
    print(f"- **Window:** {sprint.get('start_date')} → {sprint.get('end_date')}")
    print(f"- **Plane id:** {sprint.get('id')}")

print(f"\n---")
print(f"\n*Generated by `jp-progress-report.sh` on production server.*")
PYEOF

echo "$OUT_FILE" >&2

# Email digest to Braun (uses existing send-alert.py)
if [[ "$PERIOD" == "daily" || "$PERIOD" == "weekly" || "$PERIOD" == "sprint" ]]; then
    python3 -c "
import sys
sys.path.insert(0, '/home/aielevate')
try:
    from send_email import send_email
    body = open('$OUT_FILE').read()
    subj = 'JudicialPredict — $PERIOD report — $TODAY'
    send_email(to='braun.brelin@ai-elevate.ai', subject=subj, body=body, agent_id='jp-pm-auto')
    print('email sent', file=sys.stderr)
except Exception as e:
    print(f'email skipped: {e}', file=sys.stderr)
" >> "$PROJECT_DIR/.report.log" 2>&1
fi
