# Generated by Django 5.2.14 on 2026-05-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_operator_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='username',
            field=models.CharField(blank=True, help_text='Optional alphanumeric login alias. Operators may sign in with either email or username.', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Bcrypt hash.  Set via set_password(); blank = no login allowed.', max_length=128),
        ),
    ]
