#!/usr/bin/env bash
# generate_stubs.sh — regenerate grpcio stubs from protos/ into grpc_stubs/.
# Usage: bash scripts/generate_stubs.sh
# Must be run from the ml-inference-svc/ directory (or adjust SCRIPT_DIR).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SVC_DIR="$(dirname "$SCRIPT_DIR")"
PROTO_ROOT="/opt/ai-elevate/gigforge/projects/judicialpredict/protos"
OUT_DIR="$SVC_DIR/src/ml_inference_svc/grpc_stubs"

# Resolve the venv python (workspace root is two levels up from svc dir).
VENV_PYTHON="$(dirname "$SVC_DIR")/.venv/bin/python"
if [[ ! -x "$VENV_PYTHON" ]]; then
    # Fallback: any python3 on PATH
    VENV_PYTHON="$(command -v python3)"
fi

echo "[generate_stubs] proto root : $PROTO_ROOT"
echo "[generate_stubs] output dir : $OUT_DIR"
echo "[generate_stubs] python     : $VENV_PYTHON"

mkdir -p "$OUT_DIR"

# Compute SHA256 of each proto file for the stamp comment.
FEATURE_STORE_PROTO="$PROTO_ROOT/judicialpredict/data_plane/feature_store/v1/feature_store.proto"
INFERENCE_PROTO="$PROTO_ROOT/judicialpredict/ml_plane/inference/v1/inference.proto"

FS_SHA="$(sha256sum "$FEATURE_STORE_PROTO" | awk '{print $1}')"
INF_SHA="$(sha256sum "$INFERENCE_PROTO" | awk '{print $1}')"

echo "[generate_stubs] feature_store.proto SHA256: $FS_SHA"
echo "[generate_stubs] inference.proto      SHA256: $INF_SHA"

# Run protoc via grpc_tools (installed in the uv venv).
"$VENV_PYTHON" -m grpc_tools.protoc \
    --proto_path="$PROTO_ROOT" \
    --python_out="$OUT_DIR" \
    --grpc_python_out="$OUT_DIR" \
    "$FEATURE_STORE_PROTO" \
    "$INFERENCE_PROTO"

echo "[generate_stubs] protoc complete — fixing relative imports for Python packages..."

# grpc_tools generates absolute import paths that break when the stubs live
# inside a package. Walk all *_pb2_grpc.py files in the output tree.
find "$OUT_DIR" -name "*_pb2_grpc.py" | while read -r f; do
    sed -i 's/^import \(.*_pb2\) as /from . import \1 as /g' "$f" 2>/dev/null || true
done

# Create __init__.py in every intermediate package directory produced by protoc.
find "$OUT_DIR" -type d | while read -r d; do
    touch "$d/__init__.py"
done

# Write a fresh top-level __init__.py with generator stamp + re-exports.
cat > "$OUT_DIR/__init__.py" << INIT
# Generated stubs — do not edit by hand.
# Regenerated by scripts/generate_stubs.sh
# feature_store.proto SHA256: ${FS_SHA}
# inference.proto      SHA256: ${INF_SHA}

# Re-export generated modules at short names for ergonomic imports:
#   from ml_inference_svc.grpc_stubs import inference_pb2, feature_store_pb2
from ml_inference_svc.grpc_stubs.judicialpredict.data_plane.feature_store.v1 import (
    feature_store_pb2,
)
from ml_inference_svc.grpc_stubs.judicialpredict.ml_plane.inference.v1 import (
    inference_pb2,
)

__all__ = ["feature_store_pb2", "inference_pb2"]
INIT

echo "[generate_stubs] done. Files in $OUT_DIR:"
find "$OUT_DIR" -type f | sort
