// JudicialPredict API Gateway — predictCaseOutcome GraphQL mutation (S3.1 / JP-42).
//
// Sprint-3 design choice: calls ml-inference-svc over plain HTTP (POST /predict)
// rather than gRPC.  This keeps Sprint-3 scope tight while the Python service
// only exposes an HTTP FastAPI endpoint.
//
// Sprint-4 follow-up (JP-42-gRPC): add a gRPC server to ml-inference-svc and
// replace MlInferenceClient + reqwest with a tonic stub for
// InferenceService.PredictCaseOutcome defined in
// protos/ml_plane/inference.proto.  v2.14 spec §7 mandates gRPC for cross-plane
// calls; HTTP is a pragmatic Sprint-3 shortcut only.
//
// This file is NOT the decision-action layer (S3.4).  The mutation here returns
// PredictResult to the API caller; downstream wiring to the decision-action layer
// happens in S3.3 (results-view rendering).

use std::time::Instant;

use async_graphql::{Context, ErrorExtensions, InputObject, Object, SimpleObject};
use audit_recorder::{AuditEvent, AuditRecorder, AuditStatus, hash_payload};
use serde::{Deserialize, Serialize};

use crate::app::TenantId;

// ---------------------------------------------------------------------------
// HTTP client state — injected into the GraphQL schema by build_app
// ---------------------------------------------------------------------------

/// Shared reqwest client + ML inference base URL, owned once at startup and
/// injected into the schema data map so resolvers never allocate a new client.
///
/// Clone is cheap: reqwest::Client is Arc-backed.
#[derive(Clone)]
pub(crate) struct MlInferenceClient {
    pub(crate) client: reqwest::Client,
    /// Base URL for the ML inference service, e.g. "http://ml-inference-svc:8001".
    /// Set via the `ML_INFERENCE_URL` env var (default: "http://localhost:8001").
    /// Never has a trailing slash (trimmed at construction time).
    pub(crate) base_url: String,
}

// ---------------------------------------------------------------------------
// GraphQL input type
// ---------------------------------------------------------------------------

/// Tier-A/B feature inputs accepted by the predictCaseOutcome mutation.
///
/// Field names are the exact keys in ALLOWLIST_FEATURES (ml-inference-svc/predict.py).
/// Tier-C party features are intentionally absent at the type level; the ML
/// service enforces the same allowlist as a second line of defence.
///
/// async-graphql converts snake_case field names to camelCase in the SDL:
///   judge_severity → judgeSeverity, case_type → caseType, etc.
#[derive(InputObject, Serialize, Deserialize)]
pub struct PredictInput {
    pub judge_severity: f32,
    pub attorney_win_rate: f32,
    pub ideology_distance: f32,
    pub materiality_score: f32,
    pub procedural_motion_count: f32,
    pub case_type: String,
    pub jurisdiction: String,
}

// ---------------------------------------------------------------------------
// Internal wire type — deserialized from ml-inference-svc JSON response
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct MlInferenceResponse {
    p_win: f32,
    ci_lower: f32,
    ci_upper: f32,
    coverage: f32,
    model_version: String,
    predicted_at_unix: i64,
}

// ---------------------------------------------------------------------------
// GraphQL output type
// ---------------------------------------------------------------------------

/// Prediction result: calibrated win probability and 90 % conformal CI.
///
/// All probability fields are in [0, 1].  `predicted_at_unix` is the Unix
/// epoch second at which the ML service generated the prediction.
#[derive(SimpleObject)]
pub struct PredictResult {
    /// Calibrated win probability in [0, 1].
    pub p_win: f32,
    /// Conformal CI lower bound (90 % coverage by default).
    pub ci_lower: f32,
    /// Conformal CI upper bound.
    pub ci_upper: f32,
    /// Nominal CI coverage (e.g. 0.90 for 90 %).
    pub coverage: f32,
    /// MLflow run_id of the champion model that produced this prediction.
    pub model_version: String,
    /// Unix epoch seconds at which the prediction was generated by the ML service.
    pub predicted_at_unix: i64,
}

// ---------------------------------------------------------------------------
// GraphQL Mutation root
// ---------------------------------------------------------------------------

pub(crate) struct Mutation;

#[Object]
impl Mutation {
    /// Predict the outcome of a case using the JudicialPredict ML ensemble.
    ///
    /// Accepts Tier-A/B features only (see `PredictInput`).  Tier-C party
    /// features are excluded at the type level and also rejected by the ML
    /// service.
    ///
    /// Forwards the call to ml-inference-svc via HTTP POST /predict
    /// (Sprint-3 shortcut; gRPC in Sprint-4 per v2.14 spec §7).
    ///
    /// Threads `tenant_id` from the JWT into the X-Tenant-Id header so the
    /// Python audit_recorder fires on the ML side as well as here.
    ///
    /// Always writes one gateway-side audit row (fire-and-forget, non-blocking).
    ///
    /// On non-2xx responses the resolver returns a GraphQL error with a
    /// closed-code extension field `"code"`:
    ///   - `MlInferenceTimeout`     — connect or request timed out
    ///   - `MlInferenceUnavailable` — 5xx or transport error
    ///   - `MlInferenceClientError` — 4xx (bad input)
    ///
    /// Raw HTTP error details are never exposed to callers.
    async fn predict_case_outcome(
        &self,
        ctx: &Context<'_>,
        input: PredictInput,
    ) -> async_graphql::Result<PredictResult> {
        let start = Instant::now();

        // Extract tenant identity injected by jwt_middleware.
        let TenantId(tenant_id) = *ctx
            .data::<TenantId>()
            .map_err(|_| async_graphql::Error::new("missing tenant id"))?;

        let ml = ctx
            .data::<MlInferenceClient>()
            .map_err(|_| async_graphql::Error::new("ml inference client unavailable"))?;

        // Serialise input once; reuse bytes for the audit payload hash.
        let input_json = serde_json::to_vec(&input)
            .map_err(|e| async_graphql::Error::new(e.to_string()))?;

        let predict_url = format!("{}/predict", ml.base_url);

        let http_result = ml
            .client
            .post(&predict_url)
            // Thread tenant id to the ML service so its own audit_recorder fires.
            .header("X-Tenant-Id", tenant_id.to_string())
            .header("Content-Type", "application/json")
            .body(input_json.clone())
            .send()
            .await;

        let latency_ms = start.elapsed().as_millis().min(u32::MAX as u128) as u32;

        // Map HTTP/transport outcomes to (audit status, GraphQL result).
        // Raw error details are logged but never forwarded to the caller.
        let (audit_status, gql_result) = match http_result {
            Err(e) if e.is_timeout() => {
                tracing::warn!(url = %predict_url, "ml-inference-svc timed out");
                (
                    AuditStatus::Timeout,
                    Err(async_graphql::Error::new("ml inference timed out")
                        .extend_with(|_, ext| ext.set("code", "MlInferenceTimeout"))),
                )
            }
            Err(e) => {
                tracing::warn!(error = %e, url = %predict_url, "ml-inference-svc connection error");
                (
                    AuditStatus::Err,
                    Err(async_graphql::Error::new("ml inference unavailable")
                        .extend_with(|_, ext| ext.set("code", "MlInferenceUnavailable"))),
                )
            }
            Ok(resp) => {
                let status = resp.status();
                if status.is_success() {
                    match resp.json::<MlInferenceResponse>().await {
                        Ok(r) => (
                            AuditStatus::Ok,
                            Ok(PredictResult {
                                p_win: r.p_win,
                                ci_lower: r.ci_lower,
                                ci_upper: r.ci_upper,
                                coverage: r.coverage,
                                model_version: r.model_version,
                                predicted_at_unix: r.predicted_at_unix,
                            }),
                        ),
                        Err(e) => {
                            tracing::warn!(error = %e, "ml-inference-svc response parse error");
                            (
                                AuditStatus::Err,
                                Err(async_graphql::Error::new(
                                    "ml inference response parse error",
                                )
                                .extend_with(|_, ext| ext.set("code", "MlInferenceUnavailable"))),
                            )
                        }
                    }
                } else if status.is_client_error() {
                    tracing::warn!(http_status = %status, "ml-inference-svc rejected request (4xx)");
                    (
                        AuditStatus::Err,
                        Err(async_graphql::Error::new("ml inference rejected the request")
                            .extend_with(|_, ext| ext.set("code", "MlInferenceClientError"))),
                    )
                } else {
                    // 5xx or other unexpected status.
                    tracing::warn!(http_status = %status, "ml-inference-svc returned server error");
                    (
                        AuditStatus::Err,
                        Err(async_graphql::Error::new("ml inference unavailable")
                            .extend_with(|_, ext| ext.set("code", "MlInferenceUnavailable"))),
                    )
                }
            }
        };

        // Gateway-side fire-and-forget audit record.
        // Failure is intentionally swallowed — audit must never block or fail the request.
        if let Some(recorder) = ctx
            .data::<Option<AuditRecorder>>()
            .ok()
            .and_then(|r| r.as_ref())
        {
            let recorder = recorder.clone();
            let event = AuditEvent {
                actor: "api-gateway".to_string(),
                action: "predict.invoke".to_string(),
                payload_hash: hash_payload(&input_json),
                latency_ms,
                status: audit_status,
                cost_micros: None,
            };
            tokio::spawn(async move {
                if let Err(e) = recorder.record(tenant_id, event).await {
                    tracing::warn!(error = %e, "predict audit record failed (non-fatal)");
                }
            });
        }

        gql_result
    }
}

// ---------------------------------------------------------------------------
// Unit tests — pure logic, no I/O
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// PredictInput round-trips through serde JSON without loss.
    ///
    /// Covers the full field set so a future rename or missing Serialize
    /// derive breaks here rather than at runtime.
    #[test]
    fn predict_input_json_roundtrip() {
        let input = PredictInput {
            judge_severity: 0.7,
            attorney_win_rate: 0.6,
            ideology_distance: 0.3,
            materiality_score: 0.8,
            procedural_motion_count: 3.0,
            case_type: "civil".to_string(),
            jurisdiction: "Federal".to_string(),
        };

        let json = serde_json::to_string(&input).expect("serialize");
        let decoded: PredictInput = serde_json::from_str(&json).expect("deserialize");

        // f32 comparisons — 1e-6 is well within single-precision JSON round-trip.
        assert!((decoded.judge_severity - input.judge_severity).abs() < 1e-6);
        assert!((decoded.attorney_win_rate - input.attorney_win_rate).abs() < 1e-6);
        assert!((decoded.ideology_distance - input.ideology_distance).abs() < 1e-6);
        assert!((decoded.materiality_score - input.materiality_score).abs() < 1e-6);
        assert!(
            (decoded.procedural_motion_count - input.procedural_motion_count).abs() < 1e-6
        );
        assert_eq!(decoded.case_type, input.case_type);
        assert_eq!(decoded.jurisdiction, input.jurisdiction);
    }

    /// sha256 hashing of serialised PredictInput is deterministic.
    ///
    /// Two serialisations of the same value must hash identically; two
    /// inputs that differ in at least one field must hash differently.
    #[test]
    fn predict_input_hash_is_deterministic() {
        let input_a = PredictInput {
            judge_severity: 0.5,
            attorney_win_rate: 0.5,
            ideology_distance: 0.5,
            materiality_score: 0.5,
            procedural_motion_count: 1.0,
            case_type: "criminal".to_string(),
            jurisdiction: "California".to_string(),
        };

        let bytes_a1 = serde_json::to_vec(&input_a).unwrap();
        let bytes_a2 = serde_json::to_vec(&input_a).unwrap();

        let h1 = hash_payload(&bytes_a1);
        let h2 = hash_payload(&bytes_a2);

        assert_eq!(h1, h2, "identical inputs must produce identical hashes");
        assert_eq!(h1.len(), 64, "SHA-256 hex must be exactly 64 chars");

        // A different value in any field must change the digest.
        let input_b = PredictInput {
            judge_severity: 0.9, // differs
            attorney_win_rate: 0.5,
            ideology_distance: 0.5,
            materiality_score: 0.5,
            procedural_motion_count: 1.0,
            case_type: "criminal".to_string(),
            jurisdiction: "California".to_string(),
        };
        let bytes_b = serde_json::to_vec(&input_b).unwrap();
        let h3 = hash_payload(&bytes_b);

        assert_ne!(h1, h3, "distinct inputs must produce distinct hashes");
    }
}
