// JudicialPredict API Gateway — predictCaseOutcome GraphQL mutation (S3.1 / JP-42).
//
// Sprint-3 design choice: calls ml-inference-svc over plain HTTP (POST /predict)
// rather than gRPC.  This keeps Sprint-3 scope tight while the Python service
// only exposes an HTTP FastAPI endpoint.
//
// Sprint-4 follow-up (JP-42-gRPC): add a gRPC server to ml-inference-svc and
// replace MlInferenceClient + reqwest with a tonic stub for
// InferenceService.PredictCaseOutcome defined in
// protos/ml_plane/inference.proto.  v2.14 spec §7 mandates gRPC for cross-plane
// calls; HTTP is a pragmatic Sprint-3 shortcut only.
//
// This file is NOT the decision-action layer (S3.4).  The mutation here returns
// PredictResult to the API caller; downstream wiring to the decision-action layer
// happens in S3.3 (results-view rendering).

use std::sync::Arc;
use std::time::Instant;

use async_graphql::{Context, ErrorExtensions, ID, InputObject, Json, Object, SimpleObject};
use audit_recorder::{AuditEvent, AuditRecorder, AuditStatus, hash_payload};
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use sqlx::{PgPool, Row as _};
use uuid::Uuid;

use crate::app::TenantId;
use crate::auth::Claims;

// ---------------------------------------------------------------------------
// HTTP client state — injected into the GraphQL schema by build_app
// ---------------------------------------------------------------------------

/// Shared reqwest client + ML inference base URL, owned once at startup and
/// injected into the schema data map so resolvers never allocate a new client.
///
/// Clone is cheap: reqwest::Client is Arc-backed.
#[derive(Clone)]
pub(crate) struct MlInferenceClient {
    pub(crate) client: reqwest::Client,
    /// Base URL for the ML inference service, e.g. "http://ml-inference-svc:8001".
    /// Set via the `ML_INFERENCE_URL` env var (default: "http://localhost:8001").
    /// Never has a trailing slash (trimmed at construction time).
    pub(crate) base_url: String,
}

// ---------------------------------------------------------------------------
// GraphQL input type
// ---------------------------------------------------------------------------

/// Tier-A/B feature inputs accepted by the predictCaseOutcome mutation.
///
/// Field names are the exact keys in ALLOWLIST_FEATURES (ml-inference-svc/predict.py).
/// Tier-C party features are intentionally absent at the type level; the ML
/// service enforces the same allowlist as a second line of defence.
///
/// async-graphql converts snake_case field names to camelCase in the SDL:
///   judge_severity → judgeSeverity, case_type → caseType, etc.
#[derive(InputObject, Serialize, Deserialize)]
pub struct PredictInput {
    pub judge_severity: f32,
    pub attorney_win_rate: f32,
    pub ideology_distance: f32,
    pub materiality_score: f32,
    pub procedural_motion_count: f32,
    pub case_type: String,
    pub jurisdiction: String,
}

// ---------------------------------------------------------------------------
// Internal wire type — deserialized from ml-inference-svc JSON response
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct MlInferenceResponse {
    p_win: f32,
    ci_lower: f32,
    ci_upper: f32,
    coverage: f32,
    model_version: String,
    predicted_at_unix: i64,
}

// ---------------------------------------------------------------------------
// GraphQL output type
// ---------------------------------------------------------------------------

/// Prediction result: calibrated win probability and 90 % conformal CI.
///
/// All probability fields are in [0, 1].  `predicted_at_unix` is the Unix
/// epoch second at which the ML service generated the prediction.
#[derive(SimpleObject, Serialize, Deserialize)]
pub struct PredictResult {
    /// Calibrated win probability in [0, 1].
    pub p_win: f32,
    /// Conformal CI lower bound (90 % coverage by default).
    pub ci_lower: f32,
    /// Conformal CI upper bound.
    pub ci_upper: f32,
    /// Nominal CI coverage (e.g. 0.90 for 90 %).
    pub coverage: f32,
    /// MLflow run_id of the champion model that produced this prediction.
    pub model_version: String,
    /// Unix epoch seconds at which the prediction was generated by the ML service.
    pub predicted_at_unix: i64,
}

// ---------------------------------------------------------------------------
// GraphQL DTO: recommendation (output only — Decimal → String for precision)
// ---------------------------------------------------------------------------

/// Recommendation output type.
///
/// Monetary values (`expected_value_try`, `expected_value_settle`) are
/// `String` rather than `Float` so that `rust_decimal::Decimal` precision is
/// preserved end-to-end without IEEE-754 rounding in the JSON layer.
///
/// Sprint-5 follow-up: replace the $100k/$50k placeholders with real
/// operator-supplied `expected_damages` and cost-engine output.
#[derive(SimpleObject, Serialize, Deserialize, Clone)]
pub struct RecommendationDto {
    /// Recommended action: `"Try"`, `"Settle"`, or `"Borderline"`.
    pub kind: String,
    /// Three deterministic reasoning bullets produced by decision-arith.
    pub rationale_bullets: Vec<String>,
    /// Expected value of going to trial (`p_win × damages − cost`), as a
    /// decimal string (e.g. `"-20000.00"`). May be negative.
    pub expected_value_try: String,
    /// Expected value of settlement (`damages × 0.40` anchor), as a decimal
    /// string (e.g. `"40000.00"`).
    pub expected_value_settle: String,
}

// ---------------------------------------------------------------------------
// GraphQL output type: Case (S4.2 createCase result)
// ---------------------------------------------------------------------------

/// A persisted JudicialPredict case, returned by the `createCase` mutation.
///
/// `input_features` echoes the seven Tier-A/B feature fields from the request
/// as a JSON scalar so clients can replay predictions without re-keying.
///
/// Monetary values inside `recommendation` are `String` to avoid precision
/// loss at the JSON boundary.
#[derive(SimpleObject, Serialize, Deserialize)]
pub struct Case {
    /// Storage primary key (UUID v4).
    pub id: ID,
    /// Tenant this case belongs to (UUID v4 string).
    pub tenant_id: ID,
    /// The seven Tier-A/B features submitted with the request (JSON scalar).
    pub input_features: Json<PredictInput>,
    /// ML prediction output: calibrated win probability and conformal CI.
    pub prediction: PredictResult,
    /// Decision-arith recommendation with EV comparison and reasoning bullets.
    pub recommendation: RecommendationDto,
    /// UUID of the operator who submitted the case (`sub` JWT claim), if parseable.
    pub created_by: Option<ID>,
    /// ISO-8601 UTC timestamp of row creation from `cases.created_at`.
    pub created_at: String,
}

// ---------------------------------------------------------------------------
// GraphQL Mutation root
// ---------------------------------------------------------------------------

pub(crate) struct Mutation;

#[Object]
impl Mutation {
    /// Predict the outcome of a case using the JudicialPredict ML ensemble.
    ///
    /// Accepts Tier-A/B features only (see `PredictInput`).  Tier-C party
    /// features are excluded at the type level and also rejected by the ML
    /// service.
    ///
    /// Forwards the call to ml-inference-svc via HTTP POST /predict
    /// (Sprint-3 shortcut; gRPC in Sprint-4 per v2.14 spec §7).
    ///
    /// Threads `tenant_id` from the JWT into the X-Tenant-Id header so the
    /// Python audit_recorder fires on the ML side as well as here.
    ///
    /// Always writes one gateway-side audit row (fire-and-forget, non-blocking).
    ///
    /// On non-2xx responses the resolver returns a GraphQL error with a
    /// closed-code extension field `"code"`:
    ///   - `MlInferenceTimeout`     — connect or request timed out
    ///   - `MlInferenceUnavailable` — 5xx or transport error
    ///   - `MlInferenceClientError` — 4xx (bad input)
    ///
    /// Raw HTTP error details are never exposed to callers.
    async fn predict_case_outcome(
        &self,
        ctx: &Context<'_>,
        input: PredictInput,
    ) -> async_graphql::Result<PredictResult> {
        let start = Instant::now();

        // Extract tenant identity injected by jwt_middleware.
        let TenantId(tenant_id) = *ctx
            .data::<TenantId>()
            .map_err(|_| async_graphql::Error::new("missing tenant id"))?;

        let ml = ctx
            .data::<MlInferenceClient>()
            .map_err(|_| async_graphql::Error::new("ml inference client unavailable"))?;

        // Serialise input once; reuse bytes for the audit payload hash.
        let input_json = serde_json::to_vec(&input)
            .map_err(|e| async_graphql::Error::new(e.to_string()))?;

        let predict_url = format!("{}/predict", ml.base_url);

        let http_result = ml
            .client
            .post(&predict_url)
            // Thread tenant id to the ML service so its own audit_recorder fires.
            .header("X-Tenant-Id", tenant_id.to_string())
            .header("Content-Type", "application/json")
            .body(input_json.clone())
            .send()
            .await;

        let latency_ms = start.elapsed().as_millis().min(u32::MAX as u128) as u32;

        // Map HTTP/transport outcomes to (audit status, GraphQL result).
        // Raw error details are logged but never forwarded to the caller.
        let (audit_status, gql_result) = match http_result {
            Err(e) if e.is_timeout() => {
                tracing::warn!(url = %predict_url, "ml-inference-svc timed out");
                (
                    AuditStatus::Timeout,
                    Err(async_graphql::Error::new("ml inference timed out")
                        .extend_with(|_, ext| ext.set("code", "MlInferenceTimeout"))),
                )
            }
            Err(e) => {
                tracing::warn!(error = %e, url = %predict_url, "ml-inference-svc connection error");
                (
                    AuditStatus::Err,
                    Err(async_graphql::Error::new("ml inference unavailable")
                        .extend_with(|_, ext| ext.set("code", "MlInferenceUnavailable"))),
                )
            }
            Ok(resp) => {
                let status = resp.status();
                if status.is_success() {
                    match resp.json::<MlInferenceResponse>().await {
                        Ok(r) => (
                            AuditStatus::Ok,
                            Ok(PredictResult {
                                p_win: r.p_win,
                                ci_lower: r.ci_lower,
                                ci_upper: r.ci_upper,
                                coverage: r.coverage,
                                model_version: r.model_version,
                                predicted_at_unix: r.predicted_at_unix,
                            }),
                        ),
                        Err(e) => {
                            tracing::warn!(error = %e, "ml-inference-svc response parse error");
                            (
                                AuditStatus::Err,
                                Err(async_graphql::Error::new(
                                    "ml inference response parse error",
                                )
                                .extend_with(|_, ext| ext.set("code", "MlInferenceUnavailable"))),
                            )
                        }
                    }
                } else if status.is_client_error() {
                    tracing::warn!(http_status = %status, "ml-inference-svc rejected request (4xx)");
                    (
                        AuditStatus::Err,
                        Err(async_graphql::Error::new("ml inference rejected the request")
                            .extend_with(|_, ext| ext.set("code", "MlInferenceClientError"))),
                    )
                } else {
                    // 5xx or other unexpected status.
                    tracing::warn!(http_status = %status, "ml-inference-svc returned server error");
                    (
                        AuditStatus::Err,
                        Err(async_graphql::Error::new("ml inference unavailable")
                            .extend_with(|_, ext| ext.set("code", "MlInferenceUnavailable"))),
                    )
                }
            }
        };

        // Gateway-side fire-and-forget audit record.
        // Failure is intentionally swallowed — audit must never block or fail the request.
        if let Some(recorder) = ctx
            .data::<Option<AuditRecorder>>()
            .ok()
            .and_then(|r| r.as_ref())
        {
            let recorder = recorder.clone();
            let event = AuditEvent {
                actor: "api-gateway".to_string(),
                action: "predict.invoke".to_string(),
                payload_hash: hash_payload(&input_json),
                latency_ms,
                status: audit_status,
                cost_micros: None,
            };
            tokio::spawn(async move {
                if let Err(e) = recorder.record(tenant_id, event).await {
                    tracing::warn!(error = %e, "predict audit record failed (non-fatal)");
                }
            });
        }

        gql_result
    }

    /// Create and persist a case: runs prediction, computes a recommendation
    /// via decision-arith, inserts a row into `cases`, fires an audit event,
    /// and returns the full `Case` type.
    ///
    /// **Sprint-5 follow-ups (placeholder values used here):**
    /// - `expected_damages = $100,000` — replace with operator-supplied input
    ///   once the case-intake form accepts it.
    /// - `cost = $50,000`              — replace with cost-engine output
    ///   (same $50k placeholder used in S3.3).
    ///
    /// **title / jurisdiction** are derived from `PredictInput` fields and
    /// stored verbatim; Sprint-5 should expose a dedicated title field in the
    /// mutation input so operators can label cases meaningfully.
    ///
    /// The mutation fails with a GraphQL error (with a `"code"` extension) if:
    /// - The ML inference service is unreachable or returns a non-2xx status.
    /// - `DATABASE_URL` is not set (cases pool not wired).
    /// - The INSERT is rejected by RLS (tenant mismatch).
    async fn create_case(
        &self,
        ctx: &Context<'_>,
        input: PredictInput,
    ) -> async_graphql::Result<Case> {
        let start = Instant::now();

        // ── 1. Extract identity from JWT claims ──────────────────────────────
        let claims = ctx
            .data::<Claims>()
            .map_err(|_| async_graphql::Error::new("missing claims"))?
            .clone();

        let tenant_id = Uuid::parse_str(&claims.tenant_id)
            .map_err(|_| async_graphql::Error::new("invalid tenant_id in claims"))?;

        // operator_id may legitimately fail to parse for service-account tokens.
        let operator_id: Option<Uuid> = Uuid::parse_str(&claims.sub).ok();

        // ── 2. Serialise input once; reuse bytes for ML body + audit hash ────
        let input_json = serde_json::to_vec(&input)
            .map_err(|e| async_graphql::Error::new(e.to_string()))?;

        // ── 3. Call ml-inference-svc (same path as predict_case_outcome) ─────
        let ml = ctx
            .data::<MlInferenceClient>()
            .map_err(|_| async_graphql::Error::new("ml inference client unavailable"))?;

        let predict_url = format!("{}/predict", ml.base_url);

        let http_result = ml
            .client
            .post(&predict_url)
            .header("X-Tenant-Id", tenant_id.to_string())
            .header("Content-Type", "application/json")
            .body(input_json.clone())
            .send()
            .await;

        let latency_ms = start.elapsed().as_millis().min(u32::MAX as u128) as u32;

        let ml_resp = match http_result {
            Err(e) if e.is_timeout() => {
                tracing::warn!(url = %predict_url, "ml-inference-svc timed out (createCase)");
                return Err(async_graphql::Error::new("ml inference timed out")
                    .extend_with(|_, ext| ext.set("code", "MlInferenceTimeout")));
            }
            Err(e) => {
                tracing::warn!(error = %e, url = %predict_url, "ml-inference-svc error (createCase)");
                return Err(async_graphql::Error::new("ml inference unavailable")
                    .extend_with(|_, ext| ext.set("code", "MlInferenceUnavailable")));
            }
            Ok(resp) => {
                let status = resp.status();
                if status.is_success() {
                    resp.json::<MlInferenceResponse>().await.map_err(|e| {
                        tracing::warn!(error = %e, "ml response parse error (createCase)");
                        async_graphql::Error::new("ml inference response parse error")
                            .extend_with(|_, ext| ext.set("code", "MlInferenceUnavailable"))
                    })?
                } else if status.is_client_error() {
                    tracing::warn!(http_status = %status, "ml-inference-svc 4xx (createCase)");
                    return Err(
                        async_graphql::Error::new("ml inference rejected the request")
                            .extend_with(|_, ext| ext.set("code", "MlInferenceClientError")),
                    );
                } else {
                    tracing::warn!(http_status = %status, "ml-inference-svc 5xx (createCase)");
                    return Err(async_graphql::Error::new("ml inference unavailable")
                        .extend_with(|_, ext| ext.set("code", "MlInferenceUnavailable")));
                }
            }
        };

        let prediction = PredictResult {
            p_win:             ml_resp.p_win,
            ci_lower:          ml_resp.ci_lower,
            ci_upper:          ml_resp.ci_upper,
            coverage:          ml_resp.coverage,
            model_version:     ml_resp.model_version,
            predicted_at_unix: ml_resp.predicted_at_unix,
        };

        // ── 4. Compute recommendation via decision-arith ─────────────────────
        // Sprint-5: wire real expected_damages from operator intake form.
        let decision_input = decision_arith::PredictionInput {
            p_win:             f64::from(prediction.p_win),
            ci_lower:          f64::from(prediction.ci_lower),
            ci_upper:          f64::from(prediction.ci_upper),
            expected_damages:  Decimal::from(100_000u32),
        };
        // Sprint-5: replace $50k cost placeholder with cost-engine output.
        let rec = decision_arith::recommend(&decision_input, Decimal::from(50_000u32));

        let recommendation = RecommendationDto {
            kind: match rec.kind {
                decision_arith::RecommendationKind::Settle    => "Settle".to_string(),
                decision_arith::RecommendationKind::Try       => "Try".to_string(),
                decision_arith::RecommendationKind::Borderline => "Borderline".to_string(),
            },
            rationale_bullets: rec.rationale_bullets.to_vec(),
            expected_value_try:    rec.expected_value_try.to_string(),
            expected_value_settle: rec.expected_value_settle.to_string(),
        };

        // ── 5. Serialise structs to serde_json::Value for JSONB columns ───────
        let input_features_val = serde_json::to_value(&input)
            .map_err(|e| async_graphql::Error::new(e.to_string()))?;
        let prediction_val = serde_json::to_value(&prediction)
            .map_err(|e| async_graphql::Error::new(e.to_string()))?;
        let recommendation_val = serde_json::to_value(&recommendation)
            .map_err(|e| async_graphql::Error::new(e.to_string()))?;

        // ── 6. INSERT into cases (transaction for RLS SET LOCAL) ─────────────
        let pool = ctx
            .data::<Option<Arc<PgPool>>>()
            .map_err(|_| async_graphql::Error::new("cases store unavailable"))?
            .as_ref()
            .ok_or_else(|| {
                async_graphql::Error::new("cases store not configured (DATABASE_URL missing)")
            })?;

        let mut tx = pool
            .begin()
            .await
            .map_err(|e| async_graphql::Error::new(format!("cases tx begin: {e}")))?;

        // SET LOCAL so the RLS insert-policy (`tenant_id = current_tenant_id`)
        // is satisfied for the jp_app role.  Uuid::to_string() is injection-safe.
        sqlx::query(&format!(
            "SET LOCAL app.current_tenant_id = '{tenant_id}'"
        ))
        .execute(&mut *tx)
        .await
        .map_err(|e| async_graphql::Error::new(format!("SET LOCAL failed: {e}")))?;

        // `title` and `jurisdiction` are NOT NULL in the baseline schema.
        // Sprint-5: accept `title` from the operator case-intake form.
        let title = format!("{} case", input.case_type);

        let row = sqlx::query(
            r#"
            INSERT INTO cases
                (tenant_id, title, jurisdiction,
                 input_features, prediction, recommendation, created_by)
            VALUES
                ($1, $2, $3, $4, $5, $6, $7)
            RETURNING id, created_at::text AS created_at_s
            "#,
        )
        .bind(tenant_id)
        .bind(&title)
        .bind(&input.jurisdiction)
        .bind(&input_features_val)
        .bind(&prediction_val)
        .bind(&recommendation_val)
        .bind(operator_id)
        .fetch_one(&mut *tx)
        .await
        .map_err(|e| async_graphql::Error::new(format!("case insert failed: {e}")))?;

        tx.commit()
            .await
            .map_err(|e| async_graphql::Error::new(format!("cases tx commit: {e}")))?;

        let case_id: Uuid = row
            .try_get("id")
            .map_err(|e| async_graphql::Error::new(format!("row.id: {e}")))?;
        let created_at_s: String = row
            .try_get("created_at_s")
            .map_err(|e| async_graphql::Error::new(format!("row.created_at: {e}")))?;

        // ── 7. Fire-and-forget audit record ──────────────────────────────────
        // Failure is intentionally swallowed — audit must never block the path.
        if let Some(recorder) = ctx
            .data::<Option<AuditRecorder>>()
            .ok()
            .and_then(|r| r.as_ref())
        {
            let recorder = recorder.clone();
            let event = AuditEvent {
                actor:        "api-gateway".to_string(),
                action:       "case.created".to_string(),
                payload_hash: hash_payload(&input_json),
                latency_ms,
                status:       AuditStatus::Ok,
                cost_micros:  None,
            };
            tokio::spawn(async move {
                if let Err(e) = recorder.record(tenant_id, event).await {
                    tracing::warn!(error = %e, "createCase audit record failed (non-fatal)");
                }
            });
        }

        // ── 8. Return the full Case ───────────────────────────────────────────
        Ok(Case {
            id:             ID::from(case_id.to_string()),
            tenant_id:      ID::from(tenant_id.to_string()),
            input_features: Json(input),
            prediction,
            recommendation,
            created_by:     operator_id.map(|id| ID::from(id.to_string())),
            created_at:     created_at_s,
        })
    }
}

// ---------------------------------------------------------------------------
// Unit tests — pure logic, no I/O
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// PredictInput round-trips through serde JSON without loss.
    ///
    /// Covers the full field set so a future rename or missing Serialize
    /// derive breaks here rather than at runtime.
    #[test]
    fn predict_input_json_roundtrip() {
        let input = PredictInput {
            judge_severity: 0.7,
            attorney_win_rate: 0.6,
            ideology_distance: 0.3,
            materiality_score: 0.8,
            procedural_motion_count: 3.0,
            case_type: "civil".to_string(),
            jurisdiction: "Federal".to_string(),
        };

        let json = serde_json::to_string(&input).expect("serialize");
        let decoded: PredictInput = serde_json::from_str(&json).expect("deserialize");

        // f32 comparisons — 1e-6 is well within single-precision JSON round-trip.
        assert!((decoded.judge_severity - input.judge_severity).abs() < 1e-6);
        assert!((decoded.attorney_win_rate - input.attorney_win_rate).abs() < 1e-6);
        assert!((decoded.ideology_distance - input.ideology_distance).abs() < 1e-6);
        assert!((decoded.materiality_score - input.materiality_score).abs() < 1e-6);
        assert!(
            (decoded.procedural_motion_count - input.procedural_motion_count).abs() < 1e-6
        );
        assert_eq!(decoded.case_type, input.case_type);
        assert_eq!(decoded.jurisdiction, input.jurisdiction);
    }

    /// sha256 hashing of serialised PredictInput is deterministic.
    ///
    /// Two serialisations of the same value must hash identically; two
    /// inputs that differ in at least one field must hash differently.
    #[test]
    fn predict_input_hash_is_deterministic() {
        let input_a = PredictInput {
            judge_severity: 0.5,
            attorney_win_rate: 0.5,
            ideology_distance: 0.5,
            materiality_score: 0.5,
            procedural_motion_count: 1.0,
            case_type: "criminal".to_string(),
            jurisdiction: "California".to_string(),
        };

        let bytes_a1 = serde_json::to_vec(&input_a).unwrap();
        let bytes_a2 = serde_json::to_vec(&input_a).unwrap();

        let h1 = hash_payload(&bytes_a1);
        let h2 = hash_payload(&bytes_a2);

        assert_eq!(h1, h2, "identical inputs must produce identical hashes");
        assert_eq!(h1.len(), 64, "SHA-256 hex must be exactly 64 chars");

        // A different value in any field must change the digest.
        let input_b = PredictInput {
            judge_severity: 0.9, // differs
            attorney_win_rate: 0.5,
            ideology_distance: 0.5,
            materiality_score: 0.5,
            procedural_motion_count: 1.0,
            case_type: "criminal".to_string(),
            jurisdiction: "California".to_string(),
        };
        let bytes_b = serde_json::to_vec(&input_b).unwrap();
        let h3 = hash_payload(&bytes_b);

        assert_ne!(h1, h3, "distinct inputs must produce distinct hashes");
    }

    /// `Case` serializes through serde_json with `expected_value_try` as a
    /// JSON *string*, not a JSON number.
    ///
    /// This guards the invariant that `RecommendationDto` stores monetary
    /// amounts as `String` (preserving `Decimal` precision) even after a
    /// serde round-trip through an intermediate JSON value.
    #[test]
    fn case_serializes_with_decimal_as_string() {
        let rec = RecommendationDto {
            kind: "Try".to_string(),
            rationale_bullets: vec![
                "P(win) 0.80 with 90% CI [0.65, 0.92]".to_string(),
                "Expected value at trial $70000.00 vs. expected settlement value $40000.00"
                    .to_string(),
                "Trial EV exceeds settlement and lower CI bound is above 0.55".to_string(),
            ],
            expected_value_try:    "70000.00".to_string(),
            expected_value_settle: "40000.00".to_string(),
        };
        let case = Case {
            id:        ID::from("00000000-0000-0000-0000-000000000001"),
            tenant_id: ID::from("00000000-0000-0000-0000-000000000002"),
            input_features: Json(PredictInput {
                judge_severity:          0.7,
                attorney_win_rate:       0.6,
                ideology_distance:       0.3,
                materiality_score:       0.8,
                procedural_motion_count: 3.0,
                case_type:               "civil".to_string(),
                jurisdiction:            "Federal".to_string(),
            }),
            prediction: PredictResult {
                p_win:             0.72,
                ci_lower:          0.61,
                ci_upper:          0.83,
                coverage:          0.90,
                model_version:     "test-run-abc".to_string(),
                predicted_at_unix: 1_746_748_800,
            },
            recommendation: rec,
            created_by:  None,
            created_at:  "2026-05-10T12:00:00Z".to_string(),
        };

        let json_str = serde_json::to_string(&case).expect("Case must serialize to JSON");
        let value: serde_json::Value =
            serde_json::from_str(&json_str).expect("serialized Case must parse as JSON");

        // expected_value_try is stored as String in RecommendationDto;
        // it must round-trip as a JSON string (not a JSON number).
        let ev_try = &value["recommendation"]["expected_value_try"];
        assert!(
            ev_try.is_string(),
            "expected_value_try must be a JSON string, not a number; got: {ev_try}"
        );
        assert_eq!(
            ev_try.as_str().unwrap(),
            "70000.00",
            "expected_value_try string value must round-trip exactly"
        );
    }

    /// `RecommendationDto` serializes and deserializes deterministically
    /// (same in → same JSON → same out).
    #[test]
    fn recommendation_dto_round_trip() {
        let dto = RecommendationDto {
            kind: "Borderline".to_string(),
            rationale_bullets: vec![
                "P(win) 0.50 with 90% CI [0.45, 0.60]".to_string(),
                "Expected value at trial $5000.00 vs. expected settlement value $40000.00"
                    .to_string(),
                "Outcome is borderline: CI lower bound (0.45) falls between thresholds".to_string(),
            ],
            expected_value_try:    "5000.00".to_string(),
            expected_value_settle: "40000.00".to_string(),
        };

        let json_str =
            serde_json::to_string(&dto).expect("RecommendationDto must serialize to JSON");
        let decoded: RecommendationDto =
            serde_json::from_str(&json_str).expect("RecommendationDto must deserialize from JSON");

        assert_eq!(decoded.kind,              dto.kind);
        assert_eq!(decoded.rationale_bullets, dto.rationale_bullets);
        assert_eq!(decoded.expected_value_try,    dto.expected_value_try);
        assert_eq!(decoded.expected_value_settle, dto.expected_value_settle);
    }
}
