# Generated by Django 5.2.14 on 2026-05-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('subject_id', models.TextField(blank=True, null=True)),
                ('table_name', models.TextField()),
                ('row_pk', models.TextField(blank=True, null=True)),
                ('action', models.TextField()),
                ('reason_code', models.TextField(blank=True, null=True)),
                ('ts', models.DateTimeField(db_column='ts')),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('cost_micros', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Audit log entry',
                'verbose_name_plural': 'Audit log entries',
                'db_table': 'audit_log',
                'ordering': ['-ts'],
                'managed': False,
            },
        ),
    ]
