# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from judicialpredict.ml_plane.inference.v1 import inference_pb2 as judicialpredict_dot_ml__plane_dot_inference_dot_v1_dot_inference__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in judicialpredict/ml_plane/inference/v1/inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub(object):
    """InferenceService provides case-outcome predictions from the Python ML plane.
    Called by the Rust api-gateway to serve the case workspace UI.
    See ADR-001 §Python ML plane and ADR-002 for the gRPC contract guarantees.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictCaseOutcome = channel.unary_unary(
                '/judicialpredict.ml_plane.inference.v1.InferenceService/PredictCaseOutcome',
                request_serializer=judicialpredict_dot_ml__plane_dot_inference_dot_v1_dot_inference__pb2.PredictCaseOutcomeRequest.SerializeToString,
                response_deserializer=judicialpredict_dot_ml__plane_dot_inference_dot_v1_dot_inference__pb2.PredictCaseOutcomeResponse.FromString,
                _registered_method=True)


class InferenceServiceServicer(object):
    """InferenceService provides case-outcome predictions from the Python ML plane.
    Called by the Rust api-gateway to serve the case workspace UI.
    See ADR-001 §Python ML plane and ADR-002 for the gRPC contract guarantees.
    """

    def PredictCaseOutcome(self, request, context):
        """PredictCaseOutcome returns a point-estimate win probability, a conformal
        prediction interval, and SHAP feature attributions for a single case.
        Returns NOT_FOUND if the case_id is unknown to the feature store.
        Returns FAILED_PRECONDITION if required features are missing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictCaseOutcome': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictCaseOutcome,
                    request_deserializer=judicialpredict_dot_ml__plane_dot_inference_dot_v1_dot_inference__pb2.PredictCaseOutcomeRequest.FromString,
                    response_serializer=judicialpredict_dot_ml__plane_dot_inference_dot_v1_dot_inference__pb2.PredictCaseOutcomeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'judicialpredict.ml_plane.inference.v1.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('judicialpredict.ml_plane.inference.v1.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """InferenceService provides case-outcome predictions from the Python ML plane.
    Called by the Rust api-gateway to serve the case workspace UI.
    See ADR-001 §Python ML plane and ADR-002 for the gRPC contract guarantees.
    """

    @staticmethod
    def PredictCaseOutcome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/judicialpredict.ml_plane.inference.v1.InferenceService/PredictCaseOutcome',
            judicialpredict_dot_ml__plane_dot_inference_dot_v1_dot_inference__pb2.PredictCaseOutcomeRequest.SerializeToString,
            judicialpredict_dot_ml__plane_dot_inference_dot_v1_dot_inference__pb2.PredictCaseOutcomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
