# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from judicialpredict.data_plane.feature_store.v1 import feature_store_pb2 as judicialpredict_dot_data__plane_dot_feature__store_dot_v1_dot_feature__store__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in judicialpredict/data_plane/feature_store/v1/feature_store_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FeatureStoreServiceStub(object):
    """FeatureStoreService is the authoritative API for reading and writing
    compliance-tiered features on the Rust data plane.
    Consumed by the Python ML plane via gRPC (grpcio stubs generated from
    this file). See ADR-001 §gRPC contract boundary and ADR-002.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFeature = channel.unary_unary(
                '/judicialpredict.data_plane.feature_store.v1.FeatureStoreService/GetFeature',
                request_serializer=judicialpredict_dot_data__plane_dot_feature__store_dot_v1_dot_feature__store__pb2.GetFeatureRequest.SerializeToString,
                response_deserializer=judicialpredict_dot_data__plane_dot_feature__store_dot_v1_dot_feature__store__pb2.GetFeatureResponse.FromString,
                _registered_method=True)
        self.ListFeatures = channel.unary_stream(
                '/judicialpredict.data_plane.feature_store.v1.FeatureStoreService/ListFeatures',
                request_serializer=judicialpredict_dot_data__plane_dot_feature__store_dot_v1_dot_feature__store__pb2.ListFeaturesRequest.SerializeToString,
                response_deserializer=judicialpredict_dot_data__plane_dot_feature__store_dot_v1_dot_feature__store__pb2.ListFeaturesResponse.FromString,
                _registered_method=True)
        self.IngestFeature = channel.unary_unary(
                '/judicialpredict.data_plane.feature_store.v1.FeatureStoreService/IngestFeature',
                request_serializer=judicialpredict_dot_data__plane_dot_feature__store_dot_v1_dot_feature__store__pb2.IngestFeatureRequest.SerializeToString,
                response_deserializer=judicialpredict_dot_data__plane_dot_feature__store_dot_v1_dot_feature__store__pb2.IngestFeatureResponse.FromString,
                _registered_method=True)


class FeatureStoreServiceServicer(object):
    """FeatureStoreService is the authoritative API for reading and writing
    compliance-tiered features on the Rust data plane.
    Consumed by the Python ML plane via gRPC (grpcio stubs generated from
    this file). See ADR-001 §gRPC contract boundary and ADR-002.
    """

    def GetFeature(self, request, context):
        """GetFeature returns a single feature by case and feature ID.
        Returns NOT_FOUND if the feature does not exist.
        Returns PERMISSION_DENIED if a Tier-C feature is requested without
        a valid PermittedUse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFeatures(self, request, context):
        """ListFeatures streams all features for a case, respecting tier filters.
        Tier-C features are silently omitted if permitted_use is not set.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestFeature(self, request, context):
        """IngestFeature stores a derived feature. Idempotent on idempotency_key.
        Called by the feature-deriver Rust service after derivation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeatureStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFeature': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeature,
                    request_deserializer=judicialpredict_dot_data__plane_dot_feature__store_dot_v1_dot_feature__store__pb2.GetFeatureRequest.FromString,
                    response_serializer=judicialpredict_dot_data__plane_dot_feature__store_dot_v1_dot_feature__store__pb2.GetFeatureResponse.SerializeToString,
            ),
            'ListFeatures': grpc.unary_stream_rpc_method_handler(
                    servicer.ListFeatures,
                    request_deserializer=judicialpredict_dot_data__plane_dot_feature__store_dot_v1_dot_feature__store__pb2.ListFeaturesRequest.FromString,
                    response_serializer=judicialpredict_dot_data__plane_dot_feature__store_dot_v1_dot_feature__store__pb2.ListFeaturesResponse.SerializeToString,
            ),
            'IngestFeature': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestFeature,
                    request_deserializer=judicialpredict_dot_data__plane_dot_feature__store_dot_v1_dot_feature__store__pb2.IngestFeatureRequest.FromString,
                    response_serializer=judicialpredict_dot_data__plane_dot_feature__store_dot_v1_dot_feature__store__pb2.IngestFeatureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'judicialpredict.data_plane.feature_store.v1.FeatureStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('judicialpredict.data_plane.feature_store.v1.FeatureStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FeatureStoreService(object):
    """FeatureStoreService is the authoritative API for reading and writing
    compliance-tiered features on the Rust data plane.
    Consumed by the Python ML plane via gRPC (grpcio stubs generated from
    this file). See ADR-001 §gRPC contract boundary and ADR-002.
    """

    @staticmethod
    def GetFeature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/judicialpredict.data_plane.feature_store.v1.FeatureStoreService/GetFeature',
            judicialpredict_dot_data__plane_dot_feature__store_dot_v1_dot_feature__store__pb2.GetFeatureRequest.SerializeToString,
            judicialpredict_dot_data__plane_dot_feature__store_dot_v1_dot_feature__store__pb2.GetFeatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/judicialpredict.data_plane.feature_store.v1.FeatureStoreService/ListFeatures',
            judicialpredict_dot_data__plane_dot_feature__store_dot_v1_dot_feature__store__pb2.ListFeaturesRequest.SerializeToString,
            judicialpredict_dot_data__plane_dot_feature__store_dot_v1_dot_feature__store__pb2.ListFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestFeature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/judicialpredict.data_plane.feature_store.v1.FeatureStoreService/IngestFeature',
            judicialpredict_dot_data__plane_dot_feature__store_dot_v1_dot_feature__store__pb2.IngestFeatureRequest.SerializeToString,
            judicialpredict_dot_data__plane_dot_feature__store_dot_v1_dot_feature__store__pb2.IngestFeatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
