// Imperative shell: I/O via sqlx + Postgres.
// Pure logic delegates to feature-store-types.
// gRPC stubs generated by tonic-build from protos/ at build time.
//
// FUNCTIONAL-CORE note: this crate is intentionally the imperative shell;
// see feature-store-types for the pure domain ADTs.

pub use feature_store_types::{PermittedUse, Sensitivity, Tier, TieredFeature};

// gRPC server implementation (imperative shell wrapping the repo functions).
pub mod server;

// ---------------------------------------------------------------------------
// Generated tonic stubs (prost + tonic from protos/)
// ---------------------------------------------------------------------------

/// `judicialpredict.data_plane.feature_store.v1` — FeatureStoreService stubs.
pub mod judicialpredict {
    pub mod data_plane {
        pub mod feature_store {
            pub mod v1 {
                // Includes Feature, GetFeature{Request,Response},
                // ListFeatures{Request,Response}, IngestFeature{Request,Response},
                // Tier, Sensitivity, PermittedUse enum types.
                tonic::include_proto!("judicialpredict.data_plane.feature_store.v1");
            }
        }
    }
    pub mod ml_plane {
        pub mod inference {
            pub mod v1 {
                // Includes PredictCaseOutcome{Request,Response}, ShapValue,
                // ConformalInterval, ModelVariant.
                tonic::include_proto!("judicialpredict.ml_plane.inference.v1");
            }
        }
    }
}

use anyhow::{Context, Result};
use sqlx::{PgPool, Postgres, Transaction};
use uuid::Uuid;

// ---------------------------------------------------------------------------
// Native domain types (in-process; separate from the proto wire types)
// ---------------------------------------------------------------------------

/// A feature row as returned from the `features` table.
#[derive(Debug, Clone)]
pub struct FeatureRow {
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub case_id: Option<Uuid>,
    /// Stable feature identifier, e.g. "judge.reversal_rate.circuit9".
    pub name: String,
    /// JSON-encoded feature value.
    pub value: serde_json::Value,
    /// String representation of the `feature_tier` enum, e.g. "TIER_A".
    pub tier: String,
    /// String representation of the `feature_sensitivity` enum, e.g. "PUBLIC".
    pub sensitivity: String,
    pub source: String,
    pub lineage: serde_json::Value,
}

/// Payload for inserting a new feature.
#[derive(Debug)]
pub struct IngestPayload {
    pub tenant_id: Uuid,
    pub case_id: Option<Uuid>,
    /// Stable feature identifier.
    pub name: String,
    /// JSON-encoded value — must be valid JSON.
    pub value: serde_json::Value,
    /// Must be a valid `feature_tier` variant: "TIER_A" | "TIER_B" | "TIER_C" | "TIER_D".
    pub tier: String,
    /// Must be a valid `feature_sensitivity` variant: "PUBLIC" | "QUASI_PUBLIC" | "INFERRED" | "PROTECTED".
    pub sensitivity: String,
    pub source: String,
    pub lineage: serde_json::Value,
}

// ---------------------------------------------------------------------------
// Repository
// ---------------------------------------------------------------------------

/// Holds a `PgPool` and exposes feature-store operations.
///
/// The pool connects as `jp_app` (non-superuser, no BYPASSRLS) so every
/// query is subject to the Postgres row-level-security policies defined in the
/// baseline migration. Callers must call [`set_tenant_context`] before any
/// data query.
pub struct FeatureStoreRepo {
    pool: PgPool,
}

impl FeatureStoreRepo {
    /// Connect to Postgres as `jp_app` and run embedded sqlx migrations.
    ///
    /// Panics if the migrations directory is missing at compile time (embedded
    /// by sqlx via `sqlx::migrate!()`).
    pub async fn new(database_url: &str) -> Result<Self> {
        let pool = PgPool::connect(database_url)
            .await
            .context("connecting to Postgres")?;
        // Run migrations as the pool owner. The jp_app role was granted SELECT on
        // _sqlx_migrations in migration 20260507120002.
        sqlx::migrate!()
            .run(&pool)
            .await
            .context("running sqlx migrations")?;
        Ok(Self { pool })
    }

    pub fn pool(&self) -> &PgPool {
        &self.pool
    }
}

// ---------------------------------------------------------------------------
// Tenant context — must be called before any data query
// ---------------------------------------------------------------------------

/// Begin a transaction and `SET LOCAL app.current_tenant_id` so Postgres RLS
/// evaluates the correct tenant isolation policy for every subsequent query in
/// the transaction.
///
/// Returns the open transaction. The caller is responsible for committing or
/// rolling back.
pub async fn set_tenant_context(
    pool: &PgPool,
    tenant_id: Uuid,
) -> Result<Transaction<'_, Postgres>> {
    let mut tx = pool.begin().await.context("begin transaction")?;
    // SET LOCAL does not support bind parameters ($1) in Postgres — the UUID
    // must be embedded directly. We validate it is a UUID before interpolating
    // so there is no injection risk (Uuid::to_string() always yields a
    // well-formed xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx literal).
    let sql = format!("SET LOCAL app.current_tenant_id = '{tenant_id}'");
    sqlx::query(&sql)
        .execute(&mut *tx)
        .await
        .context("SET LOCAL app.current_tenant_id")?;
    Ok(tx)
}

// ---------------------------------------------------------------------------
// Feature queries — all operate inside a tenant-context transaction
// ---------------------------------------------------------------------------

/// Look up a single feature by its database primary key (UUID).
///
/// Returns `None` if the feature does not exist **or** if RLS filters it
/// out (i.e., the feature belongs to a different tenant).
///
/// The explicit `tenant_id` WHERE clause provides defence-in-depth on top
/// of the RLS policy — both must agree for a row to be returned.
pub async fn get_feature(
    tx: &mut Transaction<'_, Postgres>,
    feature_id: Uuid,
    tenant_id: Uuid,
) -> Result<Option<FeatureRow>> {
    // Use runtime query (no macros) so DATABASE_URL is not required at compile time.
    let row = sqlx::query_as::<_, (Uuid, Uuid, Option<Uuid>, String, serde_json::Value, String, String, String, serde_json::Value)>(
        r#"
        SELECT
            id,
            tenant_id,
            case_id,
            name,
            value,
            tier::text        AS tier,
            sensitivity::text AS sensitivity,
            source,
            lineage
        FROM features
        WHERE id = $1
          AND tenant_id = $2
        "#,
    )
    .bind(feature_id)
    .bind(tenant_id)
    .fetch_optional(&mut **tx)
    .await
    .context("get_feature query")?;

    Ok(row.map(|(id, tenant_id, case_id, name, value, tier, sensitivity, source, lineage)| {
        FeatureRow { id, tenant_id, case_id, name, value, tier, sensitivity, source, lineage }
    }))
}

/// List all features for a case, respecting tenant RLS isolation.
///
/// Returns an empty Vec if the case has no features or belongs to a
/// different tenant.
pub async fn list_features_for_case(
    tx: &mut Transaction<'_, Postgres>,
    case_id: Uuid,
    tenant_id: Uuid,
) -> Result<Vec<FeatureRow>> {
    let rows = sqlx::query_as::<_, (Uuid, Uuid, Option<Uuid>, String, serde_json::Value, String, String, String, serde_json::Value)>(
        r#"
        SELECT
            id,
            tenant_id,
            case_id,
            name,
            value,
            tier::text        AS tier,
            sensitivity::text AS sensitivity,
            source,
            lineage
        FROM features
        WHERE case_id = $1
          AND tenant_id = $2
        ORDER BY created_at ASC
        "#,
    )
    .bind(case_id)
    .bind(tenant_id)
    .fetch_all(&mut **tx)
    .await
    .context("list_features_for_case query")?;

    Ok(rows
        .into_iter()
        .map(|(id, tenant_id, case_id, name, value, tier, sensitivity, source, lineage)| {
            FeatureRow { id, tenant_id, case_id, name, value, tier, sensitivity, source, lineage }
        })
        .collect())
}

/// Insert a derived feature into the feature store.
///
/// Returns the newly-assigned UUID (the storage primary key).
/// The caller must commit the transaction after a successful ingest.
pub async fn ingest_feature(
    tx: &mut Transaction<'_, Postgres>,
    payload: IngestPayload,
) -> Result<Uuid> {
    // Cast string parameters to the custom enum types in SQL.
    let id: Uuid = sqlx::query_scalar(
        r#"
        INSERT INTO features
            (tenant_id, case_id, name, value, tier, sensitivity, source, lineage)
        VALUES
            ($1, $2, $3, $4, $5::feature_tier, $6::feature_sensitivity, $7, $8)
        RETURNING id
        "#,
    )
    .bind(payload.tenant_id)
    .bind(payload.case_id)
    .bind(payload.name)
    .bind(payload.value)
    .bind(payload.tier)
    .bind(payload.sensitivity)
    .bind(payload.source)
    .bind(payload.lineage)
    .fetch_one(&mut **tx)
    .await
    .context("ingest_feature insert")?;

    Ok(id)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use prost::Message;
    use sqlx::PgPool;
    use uuid::Uuid;

    use crate::judicialpredict::data_plane::feature_store::v1::{
        GetFeatureRequest, PermittedUse as ProtoPermittedUse,
    };
    use crate::judicialpredict::ml_plane::inference::v1::{
        ModelVariant, PredictCaseOutcomeRequest,
    };

    /// Proto round-trip: GetFeatureRequest encodes and decodes without loss.
    #[test]
    fn get_feature_request_round_trip() {
        let original = GetFeatureRequest {
            case_id: "case-001".to_string(),
            feature_id: "judge.reversal_rate.circuit9".to_string(),
            permitted_use: ProtoPermittedUse::DisparateImpactAudit as i32,
        };

        let mut buf = Vec::new();
        original.encode(&mut buf).expect("encode failed");
        assert!(!buf.is_empty(), "encoded bytes must be non-empty");

        let decoded = GetFeatureRequest::decode(buf.as_slice()).expect("decode failed");
        assert_eq!(decoded.case_id, original.case_id);
        assert_eq!(decoded.feature_id, original.feature_id);
        assert_eq!(decoded.permitted_use, original.permitted_use);
    }

    /// Proto round-trip: PredictCaseOutcomeRequest encodes and decodes without loss.
    #[test]
    fn predict_case_outcome_request_round_trip() {
        let original = PredictCaseOutcomeRequest {
            case_id: "case-001".to_string(),
            feature_ids: vec![
                "judge.reversal_rate.circuit9".to_string(),
                "attorney.win_rate".to_string(),
            ],
            model_variant: ModelVariant::Xgboost as i32,
            conformal_coverage: 0.90,
            trace_id: "trace-abc-123".to_string(),
        };

        let mut buf = Vec::new();
        original.encode(&mut buf).expect("encode failed");
        assert!(!buf.is_empty(), "encoded bytes must be non-empty");

        let decoded =
            PredictCaseOutcomeRequest::decode(buf.as_slice()).expect("decode failed");
        assert_eq!(decoded.case_id, original.case_id);
        assert_eq!(decoded.feature_ids, original.feature_ids);
        assert_eq!(decoded.model_variant, original.model_variant);
        assert!(
            (decoded.conformal_coverage - original.conformal_coverage).abs() < f64::EPSILON
        );
        assert_eq!(decoded.trace_id, original.trace_id);
    }

    /// Integration test: proves RLS is enforced at the Rust layer.
    ///
    /// Requires `DATABASE_URL` env var pointing at a live Postgres with
    /// migrations applied (e.g. the docker-compose dev stack).
    /// Skipped automatically if `DATABASE_URL` is not set.
    #[tokio::test]
    async fn rls_enforces_tenant_isolation() {
        let db_url = match std::env::var("DATABASE_URL") {
            Ok(u) => u,
            Err(_) => {
                eprintln!("DATABASE_URL not set — skipping RLS integration test");
                return;
            }
        };

        // Use a raw pool — migrations are already applied by the test harness
        // (or by running `sqlx migrate run` before the test suite). jp_app does
        // not have schema-creation privileges required to run migrations itself.
        let pool = PgPool::connect(&db_url)
            .await
            .expect("pool::connect");

        let tenant_a: Uuid = "00000000-0000-0000-0000-000000000001"
            .parse()
            .unwrap();
        let tenant_b: Uuid = "00000000-0000-0000-0000-000000000002"
            .parse()
            .unwrap();

        // ---------------------------------------------------------------
        // Insert a feature as tenant_a
        // ---------------------------------------------------------------
        let payload = crate::IngestPayload {
            tenant_id: tenant_a,
            case_id: None,
            name: "rls.test.feature".to_string(),
            value: serde_json::json!({"score": 0.75}),
            tier: "TIER_A".to_string(),
            sensitivity: "PUBLIC".to_string(),
            source: "test".to_string(),
            lineage: serde_json::json!({}),
        };

        let mut tx_a = crate::set_tenant_context(&pool, tenant_a)
            .await
            .expect("set tenant a context");
        let feature_id = crate::ingest_feature(&mut tx_a, payload)
            .await
            .expect("ingest feature");
        tx_a.commit().await.expect("commit tenant a");

        // ---------------------------------------------------------------
        // Verify tenant_a can see the feature
        // ---------------------------------------------------------------
        let mut tx_a2 = crate::set_tenant_context(&pool, tenant_a)
            .await
            .expect("set tenant a context 2");
        let found = crate::get_feature(&mut tx_a2, feature_id, tenant_a)
            .await
            .expect("get_feature as tenant_a");
        tx_a2.commit().await.expect("commit tx_a2");

        assert!(
            found.is_some(),
            "tenant_a must see its own feature"
        );

        // ---------------------------------------------------------------
        // Verify tenant_b CANNOT see tenant_a's feature (RLS blocks it)
        // ---------------------------------------------------------------
        let mut tx_b = crate::set_tenant_context(&pool, tenant_b)
            .await
            .expect("set tenant b context");
        let not_found = crate::get_feature(&mut tx_b, feature_id, tenant_b)
            .await
            .expect("get_feature as tenant_b");
        tx_b.commit().await.expect("commit tx_b");

        assert!(
            not_found.is_none(),
            "tenant_b must NOT see tenant_a's feature — RLS violation"
        );

        // ---------------------------------------------------------------
        // Cleanup: delete the test feature as tenant_a (superuser bypass)
        // ---------------------------------------------------------------
        let admin_url = std::env::var("ADMIN_DATABASE_URL")
            .unwrap_or_else(|_| db_url.replace("jp_app:judicialpredict_dev_pwd", "judicialpredict:judicialpredict_dev_pwd"));
        let admin_pool = sqlx::PgPool::connect(&admin_url).await.unwrap();
        sqlx::query("DELETE FROM features WHERE id = $1")
            .bind(feature_id)
            .execute(&admin_pool)
            .await
            .expect("cleanup");
    }
}
