// Imperative shell: I/O via sqlx + Postgres.
// Pure logic delegates to feature-store-types.
// gRPC stubs generated by tonic-build from protos/ at build time.

pub use feature_store_types::{PermittedUse, Sensitivity, Tier, TieredFeature};

// ---------------------------------------------------------------------------
// Generated tonic stubs
// tonic_build writes one file per proto package into OUT_DIR, named after the
// fully-qualified package with dots replaced by underscores.
// ---------------------------------------------------------------------------

/// `judicialpredict.data_plane.feature_store.v1` — FeatureStoreService stubs.
pub mod judicialpredict {
    pub mod data_plane {
        pub mod feature_store {
            pub mod v1 {
                // Includes FeatureStore{Service}{Server,Client}, Feature,
                // GetFeature{Request,Response}, ListFeatures{Request,Response},
                // IngestFeature{Request,Response}, Tier, Sensitivity, PermittedUse.
                tonic::include_proto!("judicialpredict.data_plane.feature_store.v1");
            }
        }
    }
    pub mod ml_plane {
        pub mod inference {
            pub mod v1 {
                // Includes InferenceService{Server,Client},
                // PredictCaseOutcome{Request,Response}, ShapValue, ConformalInterval,
                // ModelVariant.
                tonic::include_proto!("judicialpredict.ml_plane.inference.v1");
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Placeholder repository — full implementation in Sprint 2 once the schema
// migration (ADR-001 §US-M1-01) is applied.
// ---------------------------------------------------------------------------

pub struct FeatureStoreRepo;

impl FeatureStoreRepo {
    pub fn new() -> Self {
        Self
    }
}

impl Default for FeatureStoreRepo {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Smoke tests — proto round-trip via prost encode/decode
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use prost::Message;

    use crate::judicialpredict::data_plane::feature_store::v1::{
        GetFeatureRequest, PermittedUse as ProtoPermittedUse,
    };
    use crate::judicialpredict::ml_plane::inference::v1::{
        ModelVariant, PredictCaseOutcomeRequest,
    };

    /// Construct a GetFeatureRequest, encode to bytes, decode back, assert equality.
    #[test]
    fn get_feature_request_round_trip() {
        let original = GetFeatureRequest {
            case_id: "case-001".to_string(),
            feature_id: "judge.reversal_rate.circuit9".to_string(),
            permitted_use: ProtoPermittedUse::DisparateImpactAudit as i32,
        };

        let mut buf = Vec::new();
        original.encode(&mut buf).expect("encode failed");
        assert!(!buf.is_empty(), "encoded bytes must be non-empty");

        let decoded = GetFeatureRequest::decode(buf.as_slice()).expect("decode failed");
        assert_eq!(decoded.case_id, original.case_id);
        assert_eq!(decoded.feature_id, original.feature_id);
        assert_eq!(decoded.permitted_use, original.permitted_use);
    }

    /// Construct a PredictCaseOutcomeRequest, encode to bytes, decode back, assert equality.
    #[test]
    fn predict_case_outcome_request_round_trip() {
        let original = PredictCaseOutcomeRequest {
            case_id: "case-001".to_string(),
            feature_ids: vec![
                "judge.reversal_rate.circuit9".to_string(),
                "attorney.win_rate".to_string(),
            ],
            model_variant: ModelVariant::Xgboost as i32,
            conformal_coverage: 0.90,
            trace_id: "trace-abc-123".to_string(),
        };

        let mut buf = Vec::new();
        original.encode(&mut buf).expect("encode failed");
        assert!(!buf.is_empty(), "encoded bytes must be non-empty");

        let decoded =
            PredictCaseOutcomeRequest::decode(buf.as_slice()).expect("decode failed");
        assert_eq!(decoded.case_id, original.case_id);
        assert_eq!(decoded.feature_ids, original.feature_ids);
        assert_eq!(decoded.model_variant, original.model_variant);
        assert!(
            (decoded.conformal_coverage - original.conformal_coverage).abs() < f64::EPSILON
        );
        assert_eq!(decoded.trace_id, original.trace_id);
    }
}
